CREATE TABLE characters (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname TEXT NOT NULL,
    gender TEXT NOT NULL,
    race TEXT NOT NULL,
    class_type TEXT NOT NULL,

    strength_original INTEGER NOT NULL,
    dexterity_original INTEGER NOT NULL,
    constitution_original INTEGER NOT NULL,
    intelligence_original INTEGER NOT NULL,
    wisdom_original INTEGER NOT NULL,
    charisma_original INTEGER NOT NULL,

    strength_total INTEGER NOT NULL,
    dexterity_total INTEGER NOT NULL,
    constitution_total INTEGER NOT NULL,
    intelligence_total INTEGER NOT NULL,
    wisdom_total INTEGER NOT NULL,
    charisma_total INTEGER NOT NULL,

    bio text,
    date_created TIMESTAMP NOT NULL DEFAULT now()
)